language: python

python: "3.8"

before_install:
  - mv config/travis_secrets.yaml config/secrets.yaml
  - mv config/android_travis config/.android
  - sed -i 's|/config/.android/adbkey|config/.android/adbkey|g' config/configuration.yaml

install:
  - pip3 install homeassistant
  - pip3 install python-dateutil

script:
  - hass -c config/ --script check_config --info all
