activate_alexa_actionable_notification:
  description: 'Activates an actionable notification on a specific echo device'
  sequence:
    - service: input_text.set_value
      data:
        entity_id: input_text.alexa_actionable_notification
        value: '{"text": "{{ text }}", "event": "{{ event_id }}"}'
    - service: media_player.play_media
      data:
        entity_id: "{{ alexa_device }}"
        media_content_type: skill
        media_content_id: !secret alexa_media_content_id
