enable_home_mode:
  mode: queued
  sequence:
    - service: script.send_notification
      data_template:
        message: 'Reativando todos os sensores'
    - service: input_boolean.turn_off
      entity_id: input_boolean.away_mode
    - wait_template: "{{ is_state('binary_sensor.door_hall_contact', 'on') }}"
      continue_on_timeout: false
    - service: script.turn_on_light_hall_at_home
    - service: script.speech_engine
      data_template:
        media_player: >
          {{speaker('livingroom')}}
        custom_message: >
          {{random_speech('welcome')}}
