enable_sleep_mode:
  mode: queued
  sequence:
    - service: script.send_notification
      data_template:
        message: 'Habilitando modo noturno!'
    - service: input_boolean.turn_off
      entity_id: input_boolean.turn_on_light_motion
    - service: input_boolean.turn_on
      entity_id: input_boolean.sleep_mode
    - service: light.turn_on
      entity_id:
        - light.lamp_side_bed_aurelio
        - light.lamp_side_bed_camila
    - service: script.turn_off_all_light
