enable_nigth_mode:
  mode: queued
  sequence:
    - service: input_boolean.turn_off
      entity_id: input_boolean.turn_on_light_motion
    - service: input_boolean.turn_on
      entity_id: input_boolean.sleep_mode
    - service: script.turn_off_all_light
