enable_away_mode:
  mode: queued
  sequence:
    - service: script.send_notification
      data_template:
        message: 'Habilitando modo ausente!'
    - service: input_boolean.turn_on
      entity_id: input_boolean.away_mode
    - service: script.turn_off_all_light
    - service: script.turn_on_light_external
