turn_off_internal_floor_1_light:
  mode: queued
  sequence:
    - service: switch.turn_off
      entity_id:
        - switch.switch_wall_garden_bottom
        - switch.switch_wall_kitchen_top
        - switch.switch_wall_kitchen_center
        - switch.switch_wall_kitchen_bottom
        - switch.switch_wall_laundry_top

        - switch.switch_side_hall
        - switch.switch_side_stairs

        - switch.switch_wall_office_top
        - switch.switch_wall_office_center
        - switch.switch_wall_office_bottom

        - switch.switch_wall_hall_1_l2_hall
        - switch.switch_wall_hall_1_l3
        - switch.switch_wall_hall_1_l4
        - switch.switch_wall_hall_3_center
        - switch.switch_wall_hall_3_bottom

    - service: light.turn_off
      entity_id:
        - light.lamps_center_livingroom
        - light.lamps_socialroom
        - light.lamp_spot_livingroom
        - light.led_americana_cct
        - light.led_americana_rgb
