turn_on_light_external:
  mode: queued
  sequence:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.turn_on_the_light_external
          state: 'on'
    - service: switch.turn_on
      entity_id:
        - switch.switch_wall_hall_2_l3_external_side
        - switch.switch_wall_hall_1_l1_garage
        - switch.switch_wall_closet_bottom
    - service: script.send_notification
      data_template:
        message: 'Luzes externas ligadas!'
