turn_off_other_light:
  mode: queued
  sequence:
    - service: switch.turn_off
      entity_id:
        - switch.switch_side_ligth_hall
        - switch.switch_side_ligth_stairs

        - switch.switch_wall_garden_top
        # virtual switch light pool
        - switch.switch_wall_garden_center
        - switch.switch_wall_garden_bottom

        - switch.switch_wall_kitchen_top
        - switch.switch_wall_kitchen_center
        - switch.switch_wall_kitchen_bottom

        - switch.switch_wall_laundry_top
        - switch.switch_wall_laundry_center
        - switch.switch_wall_laundry_bottom

        - switch.switch_wall_livingroom_top
        # Virtual switch switch.switch_wall_kitchen_top
        # - switch.switch_wall_livingroom_center
        - switch.switch_wall_livingroom_bottom

        # - switch.switch_wall_closet_top
        - switch.switch_wall_closet_center
        - switch.switch_wall_closet_bottom

        # - switch.switch_wall_bedroom_top
        # virtual switch bedside light
        - switch.switch_wall_bedroom_center
        - switch.switch_wall_bedroom_bottom

        # - switch.switch_wall_bathroom_top
        - switch.switch_wall_bathroom_center
        - switch.switch_wall_bathroom_bottom

        - switch.switch_wall_laboratory_top
        - switch.switch_wall_laboratory_center
        - switch.switch_wall_laboratory_bottom

        - switch.switch_wall_hall_3_top
        - switch.switch_wall_hall_3_center
        - switch.switch_wall_hall_3_bottom

        - switch.switch_wall_office_top
        - switch.switch_wall_office_center
        - switch.switch_wall_office_bottom

        - switch.switch_wall_bedroom_guest_1_top
        - switch.switch_wall_bedroom_guest_1_center
        - switch.switch_wall_bedroom_guest_1_bottom

        - switch.switch_wall_bedroom_guest_2_left
        - switch.switch_wall_bedroom_guest_2_center
        - switch.switch_wall_bedroom_guest_2_right

        # Garagem
        - switch.switch_wall_hall_1_l1_garage
        # Hall
        - switch.switch_wall_hall_1_l2_hall
        - switch.switch_wall_hall_1_l3
        - switch.switch_wall_hall_1_l4
        # spots
        - switch.switch_wall_hall_2_l1_minispots
        # socialroom
        - switch.switch_wall_hall_2_l2_socialroom
        # External Side
        - switch.switch_wall_hall_2_l3_external_side
        # spot socialroom
        - switch.switch_wall_hall_2_l4_spot
    - service: light.turn_off
      entity_id:
        # - light.lamp_side_bed_aurelio÷\
        # - light.lamp_side_bed_camila
        - light.lamps_center_livingroom
        # - light.lamps_bedroom
        - light.lamps_closet
        # - light.lamps_socialroom
        # - light.lamp_spot_livingroom
        - light.lamp_kiosk
        - light.lamp_machine_house

turn_off_light_on_sleep_mode_is_off:
  mode: queued
  sequence:
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
    - service: switch.turn_off
      entity_id:
        - switch.switch_wall_bathroom_top
        # - switch.switch_wall_bedroom_top
        # - switch.switch_wall_closet_top
    - service: light.turn_off
      entity_id:
        - light.lamp_side_bed_aurelio
        - light.lamp_side_bed_camila
        - light.lamps_center_livingroom

turn_off_all_light:
  mode: queued
  sequence:
    - service: script.turn_off_other_light
    - service: script.turn_off_light_on_sleep_mode_is_off
    - service: script.send_notification
      data_template:
        message: 'Luzes internas desligadas!'
