zigbee2mqtt_rename:
  alias: Zigbee2MQTT Rename
  sequence:
    service: mqtt.publish
    data_template:
      topic: zigbee2mqtt/bridge/request/device/rename
      payload_template: >-
        {
          "from": "{{ states.input_text.zigbee2mqtt_old_name.state | string }}",
          "to": "{{ states.input_text.zigbee2mqtt_new_name.state | string }}"
        }
zigbee2mqtt_remove:
  alias: Zigbee2MQTT Remove
  sequence:
    service: mqtt.publish
    data_template:
      topic: zigbee2mqtt/bridge/request/device/remove
      payload_template: "{{ states.input_text.zigbee2mqtt_remove.state | string }}"
