
- id: turn_on_the_light_with_lux_below_pool
  alias: turn_on_the_light_with_lux_below_pool
  trigger:
    - platform: state
      entity_id: input_boolean.turn_on_the_light_external
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.turn_on_the_light_external
          state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_wall_garden_top
