blueprint:
  name: Virtual Switch
  description: Turn on/off two switch
  domain: automation
  input:
    origin_switch:
    target_switch:
    target_automation:

trigger:
  - platform: state
    entity_id: !input origin_switch

action:
  - service: automation.turn_off
    entity_id: !input target_automation
  - choose:
      - conditions:
          - condition: state
            entity_id: !input origin_switch
            state: 'on'
        sequence:
          - service: homeassistant.turn_on
            entity_id: !input target_switch
          - delay: 00:00:01
          - service: automation.turn_on
            entity_id: !input target_automation
  - choose:
      - conditions:
          - condition: state
            entity_id: !input origin_switch
            state: 'off'
        sequence:
          - service: homeassistant.turn_off
            entity_id: !input target_switch
          - delay: 00:00:01
          - service: automation.turn_on
            entity_id: !input target_automation
