  >-

  {%- macro iss() -%}
  {% if is_state('binary_sensor.iss', 'on') -%}
      <break time="1s" />Ha, mais uma coisa, <break time="1s" />
      Tenho algo interessante. A estação espacial internacional está acima de nós agora. Existem {{states.binary_sensor.iss.attributes ['number_of_people_in_space']}} pessoas no espaço agora.
  {% endif -%}
  {%- endmacro -%}

  {%- macro check_door_window() -%}
  {%- if is_state('group.doors', 'on') and is_state('group.windows', 'on')%}
    Detectei que algumas portas e janelas ainda estão abertas.
  {%- elif is_state('group.doors', 'on') -%}
    Detectei que alguma porta esta aberta.
  {%- elif is_state('group.windows', 'on') -%}
    Detectei que alguma janela esta aberta.
  {%- else -%}
    Todas as portas e janelas estão fechadas.
  {%- endif -%}
  {%- endmacro -%}


  {%- macro moon() -%}
    {% if states.sensor.moon.state == 'full_moon' %}
      <break time="1s" />Ha, mais uma coisa, <break time="1s" />
      {{ [
          "é lua cheia hoje à noite!",
          "é lua cheia.",
          "sabia que a lua esta enorme hoje a noite! É lua cheia.",
          "é lua cheia hoje, dia perfeito para energização!",
          "Se você quer ver a lua cheia! É hoje a noite."
      ] | random }}
    {% elif states.sensor.moon.state == 'new_moon' %}
      <break time="1s" />Ha, mais uma coisa, <break time="1s" />
      {{ [
        "Confira a lua nova hoje à noite!",
        "Ei, olhe, há lua nova hoje.",
        "A lua ainda esta pequena. Confira a lua nova."
      ] | random }}

    {% elif states.sensor.moon.state == 'waning_gibbous' %}
      <break time="1s" />Ha, mais uma coisa, <break time="1s" />
      {{ [
        "você sabia que é lua minguante hoje à noite?",
        "a lua está minguante hoje!",
        "<emphasis level=\"moderate\">nossa</emphasis> a lua esta bem fininha hoje."
      ] | random }}
    {% endif %}
  {%- endmacro -%}
  <speak>

    <p>{{ custom_message }}</p>

    {% if call_door_window == 1 %}
    <p>{{ check_door_window() }}</p>
    {% endif %}

    {% if call_after_message == 1 %}
    <p>{{ after_message }}</p>
    {% endif %}


    {% if call_no_random != 1 %}
    <p>{{ ([moon]|random)() }}</p>
    {% endif %}
  </speak>
