#
# - alias: 'when_alarm_enable_arming'
#   trigger:
#     - platform: state
#       entity_id: alarm_control_panel.ha_alarm
#       from: 'disarmed'
#       to: 'arming'
#   condition:
#   action:
#     - service: script.speech_engine
#       data_template:
#         media_player: media_player.echo_sala
#         custom_message: >
#           {{ [
#            "Estou ativando o alarme da casa em 30 segundos!",
#            "Iniciando sistema de segurança em 30 segundos!"
#            ] | random }}
#     - service: notify.AURELIO
#       data:
#         message: 'Ativando alarme em 30 segundos!'
#
# - alias: 'when_alarm_enable_armed_away'
#   trigger:
#     - platform: state
#       entity_id: alarm_control_panel.ha_alarm
#       from: 'arming'
#       to: 'armed_away'
#   condition:
#   action:
#     - service: script.speech_engine
#       data_template:
#         media_player: media_player.echo_sala
#         custom_message: >
#           {{ [
#            "Segurança ativada! Estou monitorando a casa.",
#            "Alarme ativado!",
#            "Alarme ativado, estou monitorando os sensores!"
#            ] | random }}
#     - service: notify.AURELIO
#       data:
#         message: 'Alarme ativado!'
#
# - alias: 'enable_alarm_when_famay_is_away'
#   trigger:
#     - platform: state
#       entity_id: group.family
#       from: 'home'
#       to: 'not_home'
#   condition:
#   action:
#     - service: alarm_control_panel.alarm_disarm
#       data:
#         entity_id: alarm_control_panel.ha_alarm
#         code: !secret alarm_code
#
# - alias: 'Trigger alarm while armed away'
#   trigger:
#     - platform: state
#       entity_id: group.windows
#       to: 'on'
#     - platform: state
#       entity_id: group.doors
#       to: 'on'
#   condition:
#     - condition: state
#       entity_id: alarm_control_panel.ha_alarm
#       state: armed_away
#   action:
#     service: alarm_control_panel.alarm_trigger
#     entity_id: alarm_control_panel.ha_alarm
