- id: switch_bedside_aurelio_top
  trigger:
    - platform: state
      entity_id: binary_sensor.switch_bedside_02_touch_top
      from: 'off'
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_bedside_02_button_1
    - service: light.toggle
      entity_id:
        - light.lamp_side_bed_camila

- id: switch_bedside_camila_top
  trigger:
    - platform: state
      entity_id: binary_sensor.switch_bedside_01_touch_top
      from: 'off'
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_bedside_01_button_1
    - service: light.toggle
      entity_id:
        - light.lamp_side_bed_aurelio

- id: switch_bedside_aurelio_center
  trigger:
    - platform: state
      entity_id: binary_sensor.switch_bedside_02_touch_center
      from: 'off'
      to: 'on'
  action:
    - service: light.toggle
      entity_id:
        - light.lamps_bedroom

- id: switch_bedside_camila_center
  trigger:
    - platform: state
      entity_id: binary_sensor.switch_bedside_01_touch_center
      from: 'off'
      to: 'on'
  action:
    - service: light.toggle
      entity_id:
        - light.lamps_bedroom

- id: cube_rotate_left
  trigger:
    - platform: state
      entity_id: sensor.cubo_action
      to: 'rotate_left'
  action:
    - service: light.turn_on
      entity_id:
        - light.lamp_side_bed_aurelio
        - light.lamp_side_bed_camila

- id: cube_rotate_right
  trigger:
    - platform: state
      entity_id: sensor.cubo_action
      to: 'rotate_right'
  action:
    - service: light.turn_off
      entity_id:
        - light.lamp_side_bed_aurelio
        - light.lamp_side_bed_camila

- id: cube_tap
  trigger:
    - platform: state
      entity_id: sensor.cubo_action
      to: 'tap'
  action:
    - service: light.toggle
      entity_id: light.lamps_bedroom
