#########################################################
#
# Acende luz da lateral da casa quando tem movimento
#
########################################################
- id: turn_on_the_light_external_1
  alias: turn_on_the_light_external_1
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_side_external_1_occupancy
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.turn_on_the_light_external
          state: 'on'
        - condition: state
          entity_id: switch.switch_wall_hall_2_l3_external_side
          state: 'off'
        - condition: state
          entity_id: input_boolean.turn_on_light_motion
          state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_wall_hall_2_l3_external_side
    - service: automation.turn_on
      entity_id: automation.turn_off_the_light_external_1

- id: turn_off_the_light_external_1
  alias: turn_off_the_light_external_1
  initial_state: off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_side_external_1_occupancy
      from: 'on'
      to: 'off'
      for: '00:00:30'
  condition:
  action:
    - service: switch.turn_off
      entity_id: switch.switch_wall_hall_2_l3_external_side
    - service: automation.turn_off
      entity_id: automation.turn_off_the_light_external_1

#########################################################
#
# Acende luz da lateral da casa quando tem movimento
#
########################################################
- id: turn_on_the_light_external_2
  alias: turn_on_the_light_external_2
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_side_external_2_occupancy
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.turn_on_the_light_external
          state: 'on'
        - condition: state
          entity_id: switch.switch_wall_laundry_bottom
          state: 'off'
        - condition: state
          entity_id: input_boolean.turn_on_light_motion
          state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_wall_laundry_bottom
    - service: automation.turn_on
      entity_id: automation.turn_off_the_light_external_2

- id: turn_off_the_light_external_2
  alias: turn_off_the_light_external_2
  initial_state: off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_side_external_2_occupancy
      from: 'on'
      to: 'off'
      for: '00:00:30'
  condition:
  action:
    - service: switch.turn_off
      entity_id: switch.switch_wall_laundry_bottom
    - service: automation.turn_off
      entity_id: automation.turn_off_the_light_external_2

#########################################################
#
# Acende luz do varanda quando escurecer
#
########################################################

- id: turn_on_the_light_with_lux_below_15
  alias: turn_on_the_light_with_lux_below_15
  trigger:
    - platform: state
      entity_id: input_boolean.turn_on_the_light_external
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.door_garden_contact
          state: 'on'
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'
  action:
    - service: switch.turn_on
      entity_id:
        - switch.switch_wall_garden_top
        - switch.switch_wall_closet_bottom

- id: turn_off_the_light_with_door_garden_is_closed
  alias: turn_off_the_light_with_door_garden_is_closed
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_garden_contact
      from: 'on'
      to: 'off'
      for: '00:00:10'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.switch_wall_garden_top
        - switch.switch_wall_garden_center

- id: turn_on_the_light_external_laundry
  alias: turn_on_the_light_external_laundry
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_side_external_laundry_1_occupancy
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.turn_on_the_light_external
          state: 'on'
        - condition: state
          entity_id: switch.switch_wall_laundry_bottom
          state: 'off'
        - condition: state
          entity_id: input_boolean.turn_on_light_motion
          state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_wall_laundry_bottom
    - service: automation.turn_on
      entity_id: automation.turn_off_the_light_external_laundry

- id: turn_off_the_light_external_laundry
  alias: turn_off_the_light_external_laundry
  initial_state: off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_side_external_laundry_1_occupancy
      from: 'on'
      to: 'off'
      for: '00:00:30'
  condition:
  action:
    - service: switch.turn_off
      entity_id: switch.switch_wall_laundry_bottom
    - service: automation.turn_off
      entity_id: automation.turn_off_the_light_external_laundry

- id: turn_on_the_light_away_mode
  alias: turn_on_the_light_away_mode
  trigger:
    - platform: state
      entity_id: input_boolean.turn_on_the_light_external
      from: 'off'
      to: 'on'
  condition:
  action:
    - service: script.turn_on_light_external
