- alias: Home Assistant update_interval
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.updater
          state: 'on'
  action:
    - service: notify.AURELIO
      data:
        message: >
          *HA: Nova atualização* {{"\n"}}
          Release Note: {{states.binary_sensor.updater.attributes.release_notes}}{{"\n"}}
          Version: {{states.binary_sensor.updater.attributes.newest_version}}

- alias: "System - Notify if Nabu Casa Unavailable"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.remote_ui
      to: 'unavailable'
      for:
        seconds: 60
  action:
    - service: notify.AURELIO
      data:
        message: >
          Home Assistant Cloud não esta conectado no momento!

- alias: "Purge Otimized"
  initial_state: 'on'
  trigger:
    - platform: time
      at: '01:00:00'
  action:
    - service: recorder.purge
      data:
        keep_days: 7
        repack: true
        apply_filter: true
