- id: turn_on_hall_side_ligth
  alias: turn_on_hall_side_ligth
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.door_hall_contact
        - binary_sensor.motion_hall_occupancy
        - binary_sensor.motion_stairs_occupancy
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.turn_on_the_light_inside
          state: 'on'
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.turn_on_light_motion
          state: 'on'
  action:
    - service: switch.turn_on
      entity_id: group.balizador

- id: turn_off_hall_side_ligth
  alias: turn_off_hall_side_ligth
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.door_hall_contact
        - binary_sensor.motion_hall_occupancy
        - binary_sensor.motion_stairs_occupancy
      from: 'on'
      to: 'off'
      for: '00:00:30'
  condition:
  action:
    - service: switch.turn_off
      entity_id: group.balizador
