- alias: button_scenes_4_single
  id: button_scenes_4_single
  trigger:
    - platform: state
      entity_id: sensor.button_scenes_action
      to: '4_single'
  action:
    - service: switch.turn_off
      entity_id: switch.circadian_lighting_livingroom
    - service: light.turn_on
      entity_id: light.lamps_center_livingroom
      data:
        brightness: 230
        color_temp: 320
    - service: script.speech_engine
      data_template:
        media_player: >
          {{speaker('livingroom')}}
        custom_message: >
          {{random_speech('livingroom_circadian_off')}}

- alias: button_scenes_3_single
  id: button_scenes_3_single
  trigger:
    - platform: state
      entity_id: sensor.button_scenes_action
      to: '3_single'
  action:
    - service: switch.turn_on
      entity_id: switch.circadian_lighting_livingroom
    - service: light.turn_on
      entity_id: light.lamps_center_livingroom
    - service: script.speech_engine
      data_template:
        media_player: >
          {{speaker('livingroom')}}
        custom_message: >
          {{random_speech('livingroom_circadian_on')}}

################################################################################

- alias: button_scenes_1_single
  id: button_scenes_1_single
  trigger:
    - platform: state
      entity_id: sensor.button_scenes_action
      to: '1_single'
  action:
    - service: light.toogle
      entity_id: light.merge_light_ct_rgb_bancada_cozinha
      data:
        color_temp: 200
        brightness: 46
