# - alias: when_all_windows_is_closed
#   trigger:
#     - platform: state
#       entity_id: group.windows
#       from: 'on'
#       to: 'off'
#       for: '00:00:02'
#   condition:
#     - condition: and
#       conditions:
#         - condition: time
#           after: '22:00:00'
#           before: '03:00:00'
#   action:
#     - service: script.speech_engine
#       data_template:
#         custom_message: >
#           {{ [
#            "Todas as janelas do térreo foram fechadas",
#            ] | random }}
#         call_no_random: 1
#     - service: notify.AURELIO
#       data:
#         message: 'Todas as janelas do térreo foram fechadas'
#
#
# - alias: when_all_door_is_closed
#   trigger:
#     - platform: state
#       entity_id: group.doors
#       from: 'on'
#       to: 'off'
#       for: '00:00:02'
#   condition:
#     - condition: and
#       conditions:
#         - condition: time
#           after: '22:00:00'
#           before: '03:00:00'
#   action:
#     - service: script.speech_engine
#       data_template:
#         custom_message: >
#           {{ [
#            "Todas as portas foram fechadas",
#            ] | random }}
#         call_no_random: 1
#     - service: notify.AURELIO
#       data:
#         message: 'Todas as janelas do térreo foram fechadas'
