
- alias: pool_pump_report
  trigger:
    - platform: sun
      event: sunset
      offset: '00:30:00'
  action:
    service: notify.AURELIO
    data_template:
      message: >
        Pool Pump Report: Pool Pump was on for {{states.sensor.pool_pump_running_today.attributes.value }} / {{ states.sensor.pool_pump_liter_today.state }} L today.
        ({%- if is_state('input_boolean.swimming_season', 'on') -%}
          Swimming Season / {{ states.input_number.run_pool_pump_hours_swimming_season.state | round(0) }}h
        {%- else -%}
          Off Season / {{ states.input_number.run_pool_pump_hours_off_season.state | round(0) }}h
        {%- endif -%}).
