- alias: when_start_rain
  id: when_start_rain
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.chuva_analogica
      below: 71
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
  condition:
    - condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.chuva_analogica
          below: 71
  action:
    - service: timer.start
      data:
        entity_id: timer.rain

- alias: when_start_rain_notify
  id: when_start_rain_notify
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.rain
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
  action:
    - service: notify.AURELIO
      data_template:
        message: >
          {{random_speech('rain')}}
    - condition: state
      entity_id: input_boolean.away_mode
      state: 'off'
    - service: script.speech_engine
      data_template:
        media_player: media_player.echo_sala
        custom_message: >
          {{random_speech('rain')}}
