- alias: reset_control_daily
  trigger:
    - platform: sun
      event: sunrise
      offset: "-01:00:00"
    - platform: state
      entity_id: input_boolean.sleep_mode
      to: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.turn_on_the_light_inside
    - service: input_boolean.turn_off
      entity_id: input_boolean.sleep_mode
    - service: input_boolean.turn_off
      entity_id: input_boolean.turn_on_light_motion
