- alias: when_bed_occupancy
  trigger:
    - platform: state
      entity_id: group.bed_occupancy
      from: 'off'
      to: 'on'
      for: '00:01:00'
  action:
    - service: script.enable_sleep_mode
    - service: script.speech_engine
      data_template:
        custom_message: >
          {{random_speech('sleep_mode')}}
