- alias: Home Assistant Started
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.AURELIO
      data:
        message: >
          HomeAssistant online
    - service: script.speech_engine
      data_template:
        media_player: media_player.echo_laboratory
        custom_message: >
          {{random_speech('ha_started')}}
