- alias: Home Assistant Started
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.AURELIO
      data:
        message: >
          HomeAssistant online
    - service: script.speech_engine
      data_template:
        media_player: media_player.echo_laboratory
        custom_message: >
          {{ [
           "Estou online novamente ou ativar os sensores!",
           "Pronto! Estou aqui novamente!",
           "Parece que voltei a vida. Vou monitorar a casa.",
           "Finalmente meus sistemas estão on-line novamente.",
           "Estou iniciando meus sistemas. Só um momento."
           ] | random }}
    # - service: light.turn_off
    #
