- alias: Home Assistant Started
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    - event: homeassistant_command
      event_data:
        event_id: start
    
