- alias: when_family_home_mode
  trigger:
    - platform: state
      entity_id:
        - sensor.tracker_family
      from: 'not_home'
      to: 'home'
  action:
    - service: script.enable_home_mode

- alias: when_family_at_not_home
  trigger:
    - platform: state
      entity_id:
        - sensor.tracker_family
      from: 'home'
      to: 'not_home'
      for: '00:00:05'
  action:
    - service: script.enable_away_mode
