
#########################################################
#
# Acende luz da cozinha no interruptor da sala
#
########################################################
- id: turn_on_kitchen_light_switch_wall_livingroom
  alias: turn_on_kitchen_light_switch_wall_livingroom
  trigger:
    - platform: state
      entity_id: binary_sensor.switch_livingroom_touch_center
      from: 'off'
      to: 'on'
  condition:
  action:
    - service: switch.toggle
      entity_id: switch.switch_wall_kitchen_top

- id: turn_on_bancada_light_switch_wall_livingroom
  alias: turn_on_bancada_light_switch_wall_livingroom
  trigger:
    - platform: state
      entity_id: binary_sensor.switch_livingroom_touch_bottom
      from: 'off'
      to: 'on'
  condition:
  action:
    - service: light.toggle
      entity_id: light.led_americana_cct

#########################################################
#
# Acende luz da cozinha no interruptor da sala
#
########################################################
- id: turn_on_livingroom_light_switch_wall_livingroom_top
  alias: turn_on_livingroom_light_switch_wall_livingroom_top
  trigger:
    - platform: state
      entity_id: binary_sensor.switch_livingroom_touch_top
      from: 'off'
      to: 'on'
  condition:
  action:
    - service: light.toggle
      entity_id: light.lamps_center_livingroom


#########################################################
#
# Acende luz da cozinha no interruptor da sala
#
########################################################
- id: turn_on_socialroom_light_switch_wall_livingroom
  alias: turn_on_socialroom_light_switch_wall_livingroom
  trigger:
    - platform: state
      entity_id: switch.switch_wall_livingroom_bottom
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: switch.switch_wall_livingroom_bottom
      from: 'on'
      to: 'off'
  condition:
  action:
    - service: switch.toggle
      entity_id: switch.switch_wall_hall_2_l2_socialroom


################################################################################
- alias: virtual_switch_pool_1
  id: virtual_switch_pool_1
  use_blueprint:
    path: virtual_switch.yaml
    input:
      origin_switch: switch.lamp_pool
      target_switch: switch.switch_wall_garden_center
      target_automation: automation.virtual_switch_pool_2

- alias: virtual_switch_pool_2
  id: virtual_switch_pool_2
  use_blueprint:
    path: virtual_switch.yaml
    input:
      origin_switch: switch.switch_wall_garden_center
      target_switch: switch.lamp_pool
      target_automation: automation.virtual_switch_pool_1

################################################################################
- alias: virtual_switch_bedside_1
  id: virtual_switch_bedside_1
  use_blueprint:
    path: virtual_switch.yaml
    input:
      origin_switch: group.bedside
      target_switch: switch.switch_wall_bedroom_center
      target_automation: automation.virtual_switch_bedside_2

- alias: virtual_switch_bedside_2
  id: virtual_switch_bedside_2
  use_blueprint:
    path: virtual_switch.yaml
    input:
      origin_switch: switch.switch_wall_bedroom_center
      target_switch: group.bedside
      target_automation: automation.virtual_switch_bedside_1

################################################################################
- alias: virtual_switch_hall_1
  id: virtual_switch_hall_1
  use_blueprint:
    path: virtual_switch.yaml
    input:
      origin_switch: switch.switch_wall_hall_3_center
      target_switch: switch.switch_wall_hall_1_l2_hall
      target_automation: automation.virtual_switch_hall_2

- alias: virtual_switch_hall_2
  id: virtual_switch_hall_2
  use_blueprint:
    path: virtual_switch.yaml
    input:
      origin_switch: switch.switch_wall_hall_1_l2_hall
      target_switch: switch.switch_wall_hall_3_center
      target_automation: automation.virtual_switch_hall_1


################################################################################
- alias: virtual_switch_stairs_1
  id: virtual_switch_stairs_1
  use_blueprint:
    path: virtual_switch.yaml
    input:
      origin_switch: switch.switch_wall_hall_3_bottom
      target_switch: group.balizador
      target_automation: automation.virtual_switch_stairs_2

- alias: virtual_switch_stairs_2
  id: virtual_switch_stairs_2
  use_blueprint:
    path: virtual_switch.yaml
    input:
      origin_switch: group.balizador
      target_switch: switch.switch_wall_hall_3_bottom
      target_automation: automation.virtual_switch_stairs_1
