#########################################################
#
# Acende luz da piscina (sonoff mini) através do botão central do interruptor
#
########################################################
- id: turn_on_pool_lights_with_switch_wall_garden_center
  alias: turn_on_pool_lights_with_switch_wall_garden_center
  trigger:
    - platform: state
      entity_id: switch.switch_wall_garden_center
      from: 'off'
      to: 'on'
  condition:
  action:
    - service: switch.turn_on
      entity_id: switch.lamp_pool

- id: turn_off_pool_lights_with_switch_wall_garden_center
  alias: turn_off_pool_lights_with_switch_wall_garden_center
  trigger:
    - platform: state
      entity_id: switch.switch_wall_garden_center
      from: 'on'
      to: 'off'
  condition:
  action:
    - service: switch.turn_off
      entity_id: switch.lamp_pool

#########################################################
#
# Acende luz da cozinha no interruptor da sala
#
########################################################
- id: turn_on_kitchen_light_switch_wall_livingroom
  alias: turn_on_kitchen_light_switch_wall_livingroom
  trigger:
    - platform: state
      entity_id: binary_sensor.switch_livingroom_touch_center
      from: 'off'
      to: 'on'
  condition:
  action:
    - service: switch.toggle
      entity_id: switch.switch_wall_kitchen_top

- id: turn_on_bancada_light_switch_wall_livingroom
  alias: turn_on_bancada_light_switch_wall_livingroom
  trigger:
    - platform: state
      entity_id: binary_sensor.switch_livingroom_touch_bottom
      from: 'off'
      to: 'on'
  condition:
  action:
    - service: light.toggle
      entity_id: light.led_americana_cct

#########################################################
#
# Acende luz da cozinha no interruptor da sala
#
########################################################
- id: turn_on_livingroom_light_switch_wall_livingroom_top
  alias: turn_on_livingroom_light_switch_wall_livingroom_top
  trigger:
    - platform: state
      entity_id: binary_sensor.switch_livingroom_touch_top
      from: 'off'
      to: 'on'
  condition:
  action:
    - service: light.toggle
      entity_id: light.lamps_center_livingroom


#########################################################
#
# Acende luz da cozinha no interruptor da sala
#
########################################################
- id: turn_on_socialroom_light_switch_wall_livingroom
  alias: turn_on_socialroom_light_switch_wall_livingroom
  trigger:
    - platform: state
      entity_id: switch.switch_wall_livingroom_bottom
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: switch.switch_wall_livingroom_bottom
      from: 'on'
      to: 'off'
  condition:
  action:
    - service: switch.toggle
      entity_id: switch.switch_wall_hall_2_l2_socialroom

#########################################################
#
# Acende luz do abajur no interruptor do quarto
#
########################################################
- id: turn_on_lamp_side_bed_with_switch_wall_bedroom_center
  alias: turn_on_lamp_side_bed_with_switch_wall_bedroom_center
  trigger:
    - platform: state
      entity_id: switch.switch_wall_bedroom_center
      from: 'off'
      to: 'on'
  condition:
  action:
    - service: light.turn_on
      entity_id:
        - light.lamp_side_bed_aurelio
        - light.lamp_side_bed_camila

- id: turn_off_lamp_side_bed_with_switch_wall_bedroom_center
  alias: turn_off_lamp_side_bed_with_switch_wall_bedroom_center
  trigger:
    - platform: state
      entity_id: switch.switch_wall_bedroom_center
      from: 'on'
      to: 'off'
  condition:
  action:
    - service: light.turn_off
      entity_id:
        - light.lamp_side_bed_aurelio
        - light.lamp_side_bed_camila

#########################################################
#
# Hall corredor
#
########################################################

- alias: virtual_switch_hall_1
  id: virtual_switch_hall_1
  trigger:
    - platform: state
      entity_id: switch.switch_wall_hall_3_center
  action:
    - service: automation.turn_on
      entity_id: automation.virtual_switch_hall_2
    - choose:
        - conditions:
            - condition: state
              entity_id: switch.switch_wall_hall_3_center
              state: 'on'
          sequence:
            - service: switch.turn_on
              entity_id: switch.switch_wall_hall_1_l2_hall
            - service: automation.turn_on
              entity_id: automation.virtual_switch_hall_2
    - choose:
        - conditions:
            - condition: state
              entity_id: switch.switch_wall_hall_3_center
              state: 'off'
          sequence:
            - service: switch.turn_off
              entity_id: switch.switch_wall_hall_1_l2_hall
            - service: automation.turn_on
              entity_id: automation.virtual_switch_hall_2

- alias: virtual_switch_hall_2
  id: virtual_switch_hall_2
  trigger:
    - platform: state
      entity_id: switch.switch_wall_hall_1_l2_hall
  action:
    - service: automation.turn_off
      entity_id: automation.virtual_switch_hall_1
    - choose:
        - conditions:
            - condition: state
              entity_id: switch.switch_wall_hall_1_l2_hall
              state: 'on'
          sequence:
            - service: switch.turn_on
              entity_id: switch.switch_wall_hall_3_center
            - service: automation.turn_on
              entity_id: automation.virtual_switch_hall_1
    - choose:
        - conditions:
            - condition: state
              entity_id: switch.switch_wall_hall_1_l2_hall
              state: 'off'
          sequence:
            - service: switch.turn_off
              entity_id: switch.switch_wall_hall_3_center
            - service: automation.turn_on
              entity_id: automation.virtual_switch_hall_1


#########################################################
#
# Hall escada
#
########################################################
- alias: virtual_switch_stairs_1
  id: virtual_switch_stairs_1
  trigger:
    - platform: state
      entity_id: switch.switch_wall_hall_3_bottom
  action:
    - service: automation.turn_on
      entity_id: automation.virtual_switch_stairs_2
    - choose:
        - conditions:
            - condition: state
              entity_id: switch.switch_wall_hall_3_bottom
              state: 'on'
          sequence:
            - service: switch.turn_on
              entity_id: group.balizador
            - service: automation.turn_on
              entity_id: automation.virtual_switch_stairs_2
    - choose:
        - conditions:
            - condition: state
              entity_id: switch.switch_wall_hall_3_bottom
              state: 'off'
          sequence:
            - service: switch.turn_off
              entity_id: group.balizador
            - service: automation.turn_on
              entity_id: automation.virtual_switch_stairs_2

- alias: virtual_switch_stairs_2
  id: virtual_switch_stairs_2
  trigger:
    - platform: state
      entity_id: group.balizador
  action:
    - service: automation.turn_off
      entity_id: automation.virtual_switch_stairs_1
    - choose:
        - conditions:
            - condition: state
              entity_id: group.balizador
              state: 'on'
          sequence:
            - service: switch.turn_on
              entity_id: switch.switch_wall_hall_3_bottom
            - service: automation.turn_on
              entity_id: automation.virtual_switch_stairs_1
    - choose:
        - conditions:
            - condition: state
              entity_id: group.balizador
              state: 'off'
          sequence:
            - service: switch.turn_off
              entity_id: switch.switch_wall_hall_3_bottom
            - service: automation.turn_on
              entity_id: automation.virtual_switch_stairs_1
