- alias: when_washing_machine_run
  trigger:
    - platform: state
      entity_id: binary_sensor.washing_machine_run
      to: 'on'
  action:
    - service: script.speech_engine
      data_template:
        media_player: >
          {{speaker('kitchen')}}
        custom_message: >
          {{random_speech('washing_machine_run')}}
        call_no_announcement: 1
        call_no_random: 1


- alias: when_washing_machine_rinse
  trigger:
    - platform: state
      entity_id: binary_sensor.washing_machine_rinse
      to: 'on'
      for: '00:02:00'
  action:
    - service: script.speech_engine
      data_template:
        media_player: >
          {{speaker('kitchen')}}
        custom_message: >
          {{random_speech('washing_machine_rinse')}}
        call_no_announcement: 1
        call_no_random: 1

- alias: when_washing_machine_end
  trigger:
    - platform: state
      entity_id: binary_sensor.washing_machine_end
      to: 'on'
  action:
    - service: script.speech_engine
      data_template:
        media_player: >
          {{speaker('kitchen')}}
        custom_message: >
          {{random_speech('washing_machine_end')}}
        call_no_announcement: 1
        call_no_random: 1
