- alias: sensor_turn_on_the_light_external
  trigger:
    - platform: numeric_state
      entity_id: sensor.lumens_garden_illuminance_lux
      below: 60
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
  condition:
    - condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.lumens_garden_illuminance_lux
          below: 60
  action:
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.turn_on_the_light_external
        - input_boolean.turn_on_the_light_inside
        - input_boolean.turn_on_light_motion
