- platform: template
  sensors:
    alexa_next_alarm_bedroom:
      value_template: >
        {% set alarm_time = as_timestamp(states('sensor.echo_sala_next_alarm')) %}
        {% set current_time = as_timestamp(states('sensor.date_time').replace(',', '')) %}
        {% set pre_time = 2 %}
        {{ current_time >= alarm_time - pre_time }}
