- platform: template
  sensors:
    tracker_aurelio:
      friendly_name: "Localização do Aurélio"
      value_template: >
          {%- if is_state('binary_sensor.mobile_aurelio_wifi_state', 'on') -%}
            {%- if is_state('sensor.mobile_wifi_connection', 'TrocoVinhoPorSenha') -%}
                home
            {%- else -%}
                not_home
            {%- endif %}
          {%- else -%}
            {%- if is_state('device_tracker.mobile', 'home') -%}
              home
            {%- else -%}
              not_home
            {%- endif %}
          {%- endif %}
      icon_template: >
          {%- if is_state('binary_sensor.mobile_aurelio_wifi_state', 'on') -%}
            {%- if is_state('sensor.mobile_wifi_connection', 'TrocoVinhoPorSenha') -%}
              mdi:home-account
            {%- else -%}
              mdi:home-outline
            {%- endif %}
          {%- else -%}
            {%- if is_state('device_tracker.mobile', 'home') -%}
              mdi:home-account
            {%- else -%}
              mdi:home-outline
            {%- endif %}
          {%- endif %}
    tracker_camila:
      friendly_name: "Localização do Camila"
      value_template: >
          {%- if is_state('binary_sensor.mobile_camila_wifi_state', 'on') -%}
            {%- if is_state('sensor.mobile_camila_wifi_connection', 'TrocoVinhoPorSenha') -%}
                home
            {%- else -%}
                not_home
            {%- endif %}
          {%- else -%}
            {%- if is_state('device_tracker.mobile_camila', 'home') -%}
              home
            {%- else -%}
              not_home
            {%- endif %}
          {%- endif %}
      icon_template: >
          {%- if is_state('binary_sensor.mobile_camila_wifi_state', 'on') -%}
            {%- if is_state('sensor.mobile_camila_wifi_connection', 'TrocoVinhoPorSenha') -%}
              mdi:home-account
            {%- else -%}
              mdi:home-outline
            {%- endif %}
          {%- else -%}
            {%- if is_state('device_tracker.mobile_camila', 'home') -%}
              mdi:home-account
            {%- else -%}
              mdi:home-outline
            {%- endif %}
          {%- endif %}
    tracker_family:
      friendly_name: "Grupo Famila"
      value_template: >
          {%- if is_state('sensor.tracker_aurelio', 'home')  or is_state('sensor.tracker_camila', 'home') -%}
            home
          {%- else -%}
            not_home
          {%- endif %}
      icon_template: >
          {%- if is_state('sensor.tracker_aurelio', 'home')  or is_state('sensor.tracker_camila', 'home') -%}
            mdi:home-account
          {%- else -%}
            mdi:home-outline
          {%- endif %}
