- platform: history_stats
  name: rain_digital
  entity_id: binary_sensor.rain_water_level_digital
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: template
  sensors:
    rain_digital_count:
      icon_template: mdi:counter
      value_template: >
        {%- if is_state('binary_sensor.rain_water_level_digital', 'on') -%}
        1
        {%- else -%}
        0
        {%- endif -%}
