
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

recorder:
  db_url: !secret mysql_host

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations
sensor: !include_dir_merge_list sensors
binary_sensor: !include binary_sensor.yaml
# script: !include scripts.yaml
script: !include_dir_merge_named scripts
scene: !include scenes.yaml
light: !include light.yaml
utility_meter: !include utility_meter.yaml
input_boolean: !include input_boolean.yaml
input_select:: !include input_select.yaml
input_number: !include input_number.yaml
switch: !include switch.yaml
input_text: !include input_text.yaml
timer: !include timer.yaml
logbook: !include logbook.yaml

lovelace:
  resources:
    - url: /local/custom_ui/mini-graph-card-bundle.js?v=0.10.0
      type: module

webhook:

pool_pump_service:
circadian_lighting:
merge_light_ct_rgb:
global_macro:
  speaker:
    default: media_player.echo_sala
    livingroom: media_player.echo_sala
    kitchen: media_player.echo_dot_cozinha
    bedroom: media_player.echo_dot_quarto
    laboratory: media_player.echo_dot_laboratorio
    socialroom: media_player.echo_dot_escritorio
  speech: !include speech.yaml

  # topic: your topic (optional, default zigbee2mqtt)
panel_iframe:
  zigbee2mqtt:
    title: 'Zigbee2Mqtt'
    url: 'http://192.168.68.100:8080/#/dashboard'
    icon: 'mdi:graphql'
  esphome:
    title: 'ESPHome'
    url: 'http://192.168.68.100:6052/'
    icon: 'mdi:memory'


telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids: !secret telegram_allowed_chat_ids
notify:
  - platform: telegram
    name: AURELIO
    chat_id: !secret telegram_aurelio
  - platform: telegram
    name: CAMILA
    chat_id: !secret telegram_camila

cloud:
  google_actions:
    filter:
      include_entities:
        - light.led_americana_cct
        - light.led_americana_rgb
        - switch.switch_wall_kitchen_top
    entity_config:
      light.led_americana_cct:
        name: Led bancada cct
        room: Cozinha
      light.led_americana_rgb:
        name: Led bancada rgb
        room: Cozinha
      switch.switch_wall_kitchen_top:
        name: Luz da cozinha
        room: Cozinha
  alexa:
    filter:
      include_entities:
        - light.lamps_center_livingroom
        - light.lamps_socialroom
        - light.lamps_bedroom
        - light.lamps_closet
        - switch.switch_wall_bathroom_top
        - switch.switch_wall_garden_center
        - switch.switch_wall_kitchen_top
        - switch.switch_wall_bedroom_top
        - sensor.weather_bedroom_temperature
        - switch.plug_fan
        - switch.switch_wall_laboratory_top
    # https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-discovery.html#display-categories
    entity_config:
      switch.switch_wall_laboratory_top:
        name: Luz
        description: Luz
        display_categories: LIGHT
      switch.plug_fan:
        name: Ventilador
        description: Ventilador
        display_categories: FAN
      light.lamps_closet:
        name: Luzes do closet
        description: Luzes do closet
        display_categories: LIGHT
      light.lamps_center_livingroom:
        name: Luzes da sala
        description: Luzes da sala
        display_categories: LIGHT
      switch.switch_wall_garden_center:
        name: Luzes da piscina
        description: Luzes da piscina
        display_categories: LIGHT
      switch.switch_wall_kitchen_top:
        name: Luz da cozinha
        description: Luz da cozinha
        display_categories: LIGHT
      switch.switch_wall_bedroom_top:
        name: Luz do quarto
        description: Luz do quarto
        display_categories: LIGHT
      switch.switch_wall_bathroom_top:
        name: Luz do banheiro
        description: Luz do banheiro
        display_categories: LIGHT
      sensor.weather_bedroom_temperature:
        name: Temperatura do quarto
        description: Temperatura do quarto
        display_categories: TEMPERATURE_SENSOR

alarm_control_panel:
  - platform: manual
    code: !secret alarm_code
    code_arm_required: true
    arming_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

camera:
  - platform: generic
    name: ISS
    still_image_url: http://staticmap.openstreetmap.de/staticmap.php?center={{ state_attr('binary_sensor.iss', 'lat') }},{{ state_attr('binary_sensor.iss', 'long') }}&zoom=4&size=865x512&maptype=mapnik&markers={{ state_attr('binary_sensor.iss', 'lat') }},{{ state_attr('binary_sensor.iss', 'long') }},lightblue
    limit_refetch_to_url_change: true

media_player:
  - platform: androidtv
    name: Amazon Fire TV
    host: !secret fire_tv
    device_class: firetv
    adbkey: "/config/.android/adbkey"
    apps:
      com.amazon.amazonvideo.livingroom: "Amazon Video"
      com.netflix.ninja: "Netflix"
      com.google.android.youtube.tv: "YouTube"
      com.google.android.tvlauncher: "Menu"
    state_detection_rules:
      'com.amazon.amazonvideo.livingroom.firetv':
        - 'playing':
            'wake_lock_size': 4  # this indentation is important!
        - 'playing':
            'wake_lock_size': 3  # this indentation is important!
        - 'paused':
            'wake_lock_size': 2  # this indentation is important!
        - 'paused':
            'wake_lock_size': 1  # this indentation is important!
        - 'standby'
      'com.amazon.tv.launcher':
        - 'playing':
            'wake_lock_size': 4  # this indentation is important!
        - 'playing':
            'wake_lock_size': 3  # this indentation is important!
        - 'paused':
            'wake_lock_size': 2  # this indentation is important!
        - 'paused':
            'wake_lock_size': 1  # this indentation is important!
        - 'standby'
      'com.netflix.ninja':
        - 'media_session_state'
