
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

recorder:
  db_url: !secret mysql_host

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations
sensor: !include_dir_merge_list sensors
binary_sensor: !include binary_sensor.yaml
# script: !include scripts.yaml
script: !include_dir_merge_named scripts
scene: !include scenes.yaml
light: !include light.yaml
utility_meter: !include utility_meter.yaml

logger:
  default: warn
  logs:
    custom_components.ct_light: debug

lovelace:
  resources:
    - url: /local/custom_ui/mini-graph-card-bundle.js?v=0.10.0
      type: module

webhook:

zigbee2mqtt_networkmap:
pool_pump_service:
circadian_lighting:
ct_light:
  # topic: your topic (optional, default zigbee2mqtt)
panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/community/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'
  zigbee2mqtt:
    title: 'Zigbee2Mqtt'
    url: 'http://192.168.68.100:8080/#/map'
    icon: 'mdi:graphql'
  esphome:
    title: 'ESPHome'
    url: 'http://192.168.68.100:6052/'
    icon: 'mdi:memory'
input_select:
  pool_pump:
    name: Pool Pump mode
    options:
      - 'Auto'
      - 'On'
      - 'Off'
    initial: 'Auto'
    icon: mdi:engine
  zigbee2mqtt_log_level:
    name: Zigbee2MQTT Log Level
    options:
      - debug
      - info
      - warn
      - error
    initial: info
    icon: mdi:format-list-bulleted
# Input number for joining time remaining (in minutes)
input_number:
  run_pool_pump_hours_swimming_season:
    name: Run Pool Pump in Swimming Season
    min: 1
    max: 8
    step: 1
    mode: slider
  run_pool_pump_hours_off_season:
    name: Run Pool Pump in Off Season
    min: 1
    max: 6
    step: 1
    mode: slider
  zigbee2mqtt_join_minutes:
    name: "Zigbee2MQTT join minutes"
    initial: 2
    min: 1
    max: 5
    step: 1
    mode: slider
  tarifa_kwh:
    name: "Valor kW/h"
    initial: 0.99776
    min: 0
    max: 10
    step: 0.001
    unit_of_measurement: "R$"
    mode: box

# Input text to input Zigbee2MQTT friendly_name for scripts
input_text:
  zigbee2mqtt_old_name:
    name: Zigbee2MQTT Old Name
    initial: ""
  zigbee2mqtt_new_name:
    name: Zigbee2MQTT New Name
    initial: ""
  zigbee2mqtt_remove:
    name: Zigbee2MQTT Remove
    initial: ""

# Timer for joining time remaining (120 sec = 2 min)
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 120

input_datetime:
  night_start:
    has_date: false
    has_time: true
    icon: 'mdi:clock-time-five-outline'
  night_end:
    has_date: false
    has_time: true
    icon: 'mdi:clock-time-five-outline'

input_boolean:
  swimming_season:
    name: Swimming Season
    icon: mdi:swim
  guest_mode:
    name: Modo Visita
    initial: off
  sleep_mode:
    name: Modo dormindo
    initial: off
  away_mode:
    name: Modo Ausente
    initial: off
  speech_notifications:
    name: Notificações sonoras
    initial: on
  text_notifications:
    name: Notificações por texto
    initial: on
  turn_on_the_light_external:
    name: Luzes externa
    initial: off
  turn_on_the_light_inside:
    name: Luzes interna
    initial: off
  turn_on_light_motion:
    name: Luzez automatica por presença
    initial: on

############## JE05 ############################


switch:
  - platform: mqtt
    name: "Zigbee2MQTT Main join"
    state_topic: "zigbee2mqtt/bridge/info"
    value_template: '{{ value_json.permit_join | lower }}'
    command_topic: "zigbee2mqtt/bridge/request/permit_join"
    payload_on: "true"
    payload_off: "false"
  - platform: circadian_lighting
    name: bedside
    lights_ct:
      - light.lamp_side_bed_aurelio
      - light.lamp_side_bed_camila
  - platform: circadian_lighting
    name: livingroom
    lights_ct:
      - light.lamps_center_livingroom
  - platform: circadian_lighting
    name: socialroom
    lights_ct:
      - light.lamps_socialroom
  - platform: circadian_lighting
    name: bedroom
    lights_ct:
      - light.lamps_bedroom
  - platform: circadian_lighting
    name: closet
    lights_ct:
      - light.lamps_closet

# Ver todos os eventos em um diário de bordo
#  _                 _                 _
# | |     ___   __ _| |__   ___   ___ | | __
# | |    / _ \ / _` | '_ \ / _ \ / _ \| |/ /
# | |___| (_) | (_| | |_) | (_) | (_) |   <
# |______\___/ \__, |_.__/ \___/ \___/|_|\_\
#              |___/
# https://www.home-assistant.io/components/logbook/
logbook:
  exclude:
    entities:
      - sensor.alexa_next_alarm_bedroom
      - sensor.automation_count
      - sensor.binary_sensor_count
      - sensor.bridge_state
      - sensor.camera_count
      - sensor.contact_main_door_battery
      - sensor.contact_main_door_linkquality
      - sensor.contact_window_livingroom_1_battery
      - sensor.contact_window_livingroom_1_linkquality
      - sensor.contact_window_livingroom_2_battery
      - sensor.contact_window_livingroom_2_linkquality
      - sensor.coordinator_version
      - sensor.cpu_temperature
      - sensor.date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.date_time_utc
      - sensor.disk_use_percent_home
      - sensor.fatura_energia
      - sensor.fatura_energia_branca
      - sensor.internet_time
      - sensor.je05_fp_a
      - sensor.je05_fp_b
      - sensor.je05_fp_c
      - sensor.je05_fp_total
      - sensor.je05_frequencia
      - sensor.je05_irms_a
      - sensor.je05_irms_b
      - sensor.je05_irms_c
      - sensor.je05_kwh_a
      - sensor.je05_kwh_b
      - sensor.je05_kwh_c
      - sensor.je05_kwh_total
      - sensor.je05_paparente_a
      - sensor.je05_paparente_b
      - sensor.je05_paparente_c
      - sensor.je05_paparente_total
      - sensor.je05_pativa_a
      - sensor.je05_pativa_b
      - sensor.je05_pativa_c
      - sensor.je05_pativa_total
      - sensor.je05_preativa_a
      - sensor.je05_preativa_b
      - sensor.je05_preativa_c
      - sensor.je05_preativa_total
      - sensor.je05_vrms_a
      - sensor.je05_vrms_b
      - sensor.je05_vrms_c
      - sensor.je05_wifi
      - sensor.lamp_livingroom_1_linkquality
      - sensor.lamp_livingroom_1_update_state
      - sensor.lamp_livingroom_2_linkquality
      - sensor.lamp_livingroom_2_update_state
      - sensor.lamp_livingroom_3_linkquality
      - sensor.lamp_livingroom_3_update_state
      - sensor.lamp_livingroom_4_linkquality
      - sensor.lamp_livingroom_4_update_state
      - sensor.lamp_side_bed_1_linkquality
      - sensor.lamp_side_bed_1_update_state
      - sensor.lamp_side_bed_2_linkquality
      - sensor.lamp_side_bed_2_update_state
      - sensor.last_boot
      - sensor.lights_count
      - sensor.m5_b_received
      - sensor.m5_b_sent
      - sensor.m5_kib_s_received
      - sensor.m5_kib_s_sent
      - sensor.m5_packets_received
      - sensor.m5_packets_s_received
      - sensor.m5_packets_s_sent
      - sensor.m5_packets_sent
      - sensor.media_player_count
      - sensor.memory_use_percent
      - sensor.mobile_aurelio_current_time_zone
      - sensor.mobile_aurelio_current_version
      - sensor.mobile_aurelio_do_not_disturb_sensor
      - sensor.mobile_aurelio_external_storage
      - sensor.mobile_aurelio_last_notification
      - sensor.mobile_aurelio_last_update_trigger
      - sensor.mobile_aurelio_phone_state
      - sensor.mobile_aurelio_public_ip_address
      - sensor.mobile_aurelio_sim_1
      - sensor.mobile_aurelio_sim_2
      - sensor.mobile_aurelio_total_rx_gb
      - sensor.mobile_aurelio_total_tx_gb
      - sensor.mobile_aurelio_volume_level_alarm
      - sensor.mobile_aurelio_volume_level_call
      - sensor.mobile_aurelio_volume_level_music
      - sensor.mobile_aurelio_volume_level_ringer
      - sensor.mobile_aurelio_wifi_frequency
      - sensor.mobile_aurelio_wifi_ip_address
      - sensor.mobile_aurelio_wifi_link_speed
      - sensor.mobile_aurelio_wifi_signal_strength
      - sensor.mobile_battery_level
      - sensor.mobile_battery_state
      - sensor.mobile_bluetooth_connection
      - sensor.mobile_camila_battery_level
      - sensor.mobile_camila_battery_state
      - sensor.mobile_camila_bluetooth_connection
      - sensor.mobile_camila_current_time_zone
      - sensor.mobile_camila_current_version
      - sensor.mobile_camila_detected_activity
      - sensor.mobile_camila_do_not_disturb_sensor
      - sensor.mobile_camila_external_storage
      - sensor.mobile_camila_geocoded_location
      - sensor.mobile_camila_internal_storage
      - sensor.mobile_camila_last_notification
      - sensor.mobile_camila_last_reboot
      - sensor.mobile_camila_last_update_trigger
      - sensor.mobile_camila_light_sensor
      - sensor.mobile_camila_mobile_rx_gb
      - sensor.mobile_camila_mobile_tx_gb
      - sensor.mobile_camila_phone_state
      - sensor.mobile_camila_pressure_sensor
      - sensor.mobile_camila_proximity_sensor
      - sensor.mobile_camila_public_ip_address
      - sensor.mobile_camila_ringer_mode
      - sensor.mobile_camila_sim_1
      - sensor.mobile_camila_sim_2
      - sensor.mobile_camila_steps_sensor
      - sensor.mobile_camila_total_rx_gb
      - sensor.mobile_camila_total_tx_gb
      - sensor.mobile_camila_volume_level_alarm
      - sensor.mobile_camila_volume_level_call
      - sensor.mobile_camila_volume_level_music
      - sensor.mobile_camila_volume_level_ringer
      - sensor.mobile_camila_wifi_frequency
      - sensor.mobile_camila_wifi_ip_address
      - sensor.mobile_camila_wifi_link_speed
      - sensor.mobile_camila_wifi_signal_strength
      - sensor.mobile_detected_activity
      - sensor.mobile_geocoded_location
      - sensor.mobile_internal_storage
      - sensor.mobile_last_reboot
      - sensor.mobile_light_sensor
      - sensor.mobile_pressure_sensor
      - sensor.mobile_proximity_sensor
      - sensor.mobile_ringer_mode
      - sensor.mobile_steps_sensor
      - sensor.mobile_wifi_connection
      - sensor.motion_hall_battery
      - sensor.motion_hall_linkquality
      - sensor.motion_livingroom_1_battery
      - sensor.motion_livingroom_1_linkquality
      - sensor.motion_side_external_battery
      - sensor.motion_side_external_illuminance
      - sensor.motion_side_external_illuminance_lux
      - sensor.motion_side_external_linkquality
      - sensor.motion_stairs_battery
      - sensor.motion_stairs_illuminance
      - sensor.motion_stairs_illuminance_lux
      - sensor.motion_stairs_linkquality
      - sensor.plug_bedroom_1_linkquality
      - sensor.plug_bedroom_2_linkquality
      - sensor.processor_use_percent
      - sensor.script_count
      - sensor.sensor_count
      - sensor.switch_count
      - sensor.switch_pool_lights_linkquality
      - sensor.switch_side_ligth_hall_linkquality
      - sensor.switch_side_ligth_stairs_linkquality
      - sensor.switch_wall_bathroom_linkquality
      - sensor.switch_wall_bedroom_linkquality
      - sensor.switch_wall_garden_linkquality
      - sensor.switch_wall_hall_3_linkquality
      - sensor.switch_wall_kitchen_linkquality
      - sensor.switch_wall_laboratory_linkquality
      - sensor.switch_wall_livingroom_linkquality
      - sensor.tarifa_fora_ponta
      - sensor.tarifa_intermediario
      - sensor.tarifa_ponta
      - sensor.temperature_bathroom_battery
      - sensor.temperature_bathroom_humidity
      - sensor.temperature_bathroom_linkquality
      - sensor.temperature_bathroom_pressure
      - sensor.time
      - sensor.time_date
      - sensor.time_online
      - sensor.time_utc
      - sensor.tracker_count
      - sensor.zigbee2mqtt_bridge_state
      - sensor.zigbee2mqtt_version
      - sensor.zwave_count
    # domains:
    #   - sun
    #   - binary_sensor
    #   - media_player
    #   - input_boolean
    #   - input_datetime
    #   - input_number
    #   - input_select
    #   - input_text
    #   - camera
    #   - script
#     - automation

# Suporte para rastrear mudanças de estado ao longo do tempo
#  _    _ _     _
# | |  | (_)   | |
# | |__| |_ ___| |_ ___  _ __ _   _
# |  __  | / __| __/ _ \| '__| | | |
# | |  | | \__ \ || (_) | |  | |_| |
# |_|  |_|_|___/\__\___/|_|   \__, |
#                             |___/
# https://www.home-assistant.io/components/history/
# history:
#   exclude:
#     domains:
#       - updater
#       - sun
#       - binary_sensor
#       - media_player
#       - input_boolean
#       - input_datetime
#       - input_number
#       - input_select
#       - input_text
#       - camera
#       - script
# #     - automation


telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - 611383381
notify:
  - platform: telegram
    name: AURELIO
    chat_id: 611383381
  - platform: telegram
    name: CAMILA
    chat_id: 1656225164

cloud:
  google_actions:
    filter:
      include_entities:
        - light.led_americana_cct
        - light.led_americana_rgb
        - switch.switch_wall_kitchen_top
    entity_config:
      light.led_americana_cct:
        name: Led bancada cct
        room: Cozinha
      light.led_americana_rgb:
        name: Led bancada rgb
        room: Cozinha
      switch.switch_wall_kitchen_top:
        name: Luz da cozinha
        room: Cozinha
  alexa:
    filter:
      include_entities:
        - light.lamps_center_livingroom
        - light.lamps_socialroom
        - light.lamps_bedroom
        - light.lamps_closet
        - switch.switch_wall_bathroom_top
        - switch.switch_wall_garden_center
        - switch.switch_wall_kitchen_top
        - switch.switch_wall_bedroom_top
        - sensor.weather_bedroom_temperature
        - switch.plug_fan
        - switch.switch_wall_laboratory_top
    # https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-discovery.html#display-categories
    entity_config:
      switch.switch_wall_laboratory_top:
        name: Luz
        description: Luz
        display_categories: LIGHT
      switch.plug_fan:
        name: Ventilador
        description: Ventilador
        display_categories: FAN
      light.lamps_closet:
        name: Luzes do closet
        description: Luzes do closet
        display_categories: LIGHT
      light.lamps_center_livingroom:
        name: Luzes da sala
        description: Luzes da sala
        display_categories: LIGHT
      switch.switch_wall_garden_center:
        name: Luzes da piscina
        description: Luzes da piscina
        display_categories: LIGHT
      switch.switch_wall_kitchen_top:
        name: Luz da cozinha
        description: Luz da cozinha
        display_categories: LIGHT
      switch.switch_wall_bedroom_top:
        name: Luz do quarto
        description: Luz do quarto
        display_categories: LIGHT
      switch.switch_wall_bathroom_top:
        name: Luz do banheiro
        description: Luz do banheiro
        display_categories: LIGHT
      sensor.weather_bedroom_temperature:
        name: Temperatura do quarto
        description: Temperatura do quarto
        display_categories: TEMPERATURE_SENSOR

alarm_control_panel:
  - platform: manual
    code: !secret alarm_code
    code_arm_required: true
    arming_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

camera:
  - platform: generic
    name: ISS
    still_image_url: http://staticmap.openstreetmap.de/staticmap.php?center={{ state_attr('binary_sensor.iss', 'lat') }},{{ state_attr('binary_sensor.iss', 'long') }}&zoom=4&size=865x512&maptype=mapnik&markers={{ state_attr('binary_sensor.iss', 'lat') }},{{ state_attr('binary_sensor.iss', 'long') }},lightblue
    limit_refetch_to_url_change: true
