zigbee_permit_join:
  name: Permitir novos devices
  initial: off
  icon: mdi:cellphone-wireless
guest_mode:
  name: Modo Guest
  initial: on
away_mode:
  name: Modo Ausente
  initial: off
speech_notifications:
  name: Notificações sonoras
  initial: on
turn_on_the_light_external:
  name: Luzes externa
  initial: off
turn_on_the_light_inside:
  name: Luzes interna
  initial: off
