exclude:
  entities:
    - sensor.alexa_next_alarm_bedroom
    - sensor.automation_count
    - sensor.binary_sensor_count
    - sensor.bridge_state
    - sensor.camera_count
    - sensor.contact_main_door_battery
    - sensor.contact_main_door_linkquality
    - sensor.contact_window_livingroom_1_battery
    - sensor.contact_window_livingroom_1_linkquality
    - sensor.contact_window_livingroom_2_battery
    - sensor.contact_window_livingroom_2_linkquality
    - sensor.coordinator_version
    - sensor.cpu_temperature
    - sensor.date
    - sensor.date_time
    - sensor.date_time_iso
    - sensor.date_time_utc
    - sensor.disk_use_percent_home
    - sensor.fatura_energia
    - sensor.fatura_energia_branca
    - sensor.internet_time
    - sensor.je05_fp_a
    - sensor.je05_fp_b
    - sensor.je05_fp_c
    - sensor.je05_fp_total
    - sensor.je05_frequencia
    - sensor.je05_irms_a
    - sensor.je05_irms_b
    - sensor.je05_irms_c
    - sensor.je05_kwh_a
    - sensor.je05_kwh_b
    - sensor.je05_kwh_c
    - sensor.je05_kwh_total
    - sensor.je05_paparente_a
    - sensor.je05_paparente_b
    - sensor.je05_paparente_c
    - sensor.je05_paparente_total
    - sensor.je05_pativa_a
    - sensor.je05_pativa_b
    - sensor.je05_pativa_c
    - sensor.je05_pativa_total
    - sensor.je05_preativa_a
    - sensor.je05_preativa_b
    - sensor.je05_preativa_c
    - sensor.je05_preativa_total
    - sensor.je05_vrms_a
    - sensor.je05_vrms_b
    - sensor.je05_vrms_c
    - sensor.je05_wifi
    - sensor.lamp_livingroom_1_linkquality
    - sensor.lamp_livingroom_1_update_state
    - sensor.lamp_livingroom_2_linkquality
    - sensor.lamp_livingroom_2_update_state
    - sensor.lamp_livingroom_3_linkquality
    - sensor.lamp_livingroom_3_update_state
    - sensor.lamp_livingroom_4_linkquality
    - sensor.lamp_livingroom_4_update_state
    - sensor.lamp_side_bed_1_linkquality
    - sensor.lamp_side_bed_1_update_state
    - sensor.lamp_side_bed_2_linkquality
    - sensor.lamp_side_bed_2_update_state
    - sensor.last_boot
    - sensor.lights_count
    - sensor.m5_b_received
    - sensor.m5_b_sent
    - sensor.m5_kib_s_received
    - sensor.m5_kib_s_sent
    - sensor.m5_packets_received
    - sensor.m5_packets_s_received
    - sensor.m5_packets_s_sent
    - sensor.m5_packets_sent
    - sensor.media_player_count
    - sensor.memory_use_percent
    - sensor.mobile_aurelio_current_time_zone
    - sensor.mobile_aurelio_current_version
    - sensor.mobile_aurelio_do_not_disturb_sensor
    - sensor.mobile_aurelio_external_storage
    - sensor.mobile_aurelio_last_notification
    - sensor.mobile_aurelio_last_update_trigger
    - sensor.mobile_aurelio_phone_state
    - sensor.mobile_aurelio_public_ip_address
    - sensor.mobile_aurelio_sim_1
    - sensor.mobile_aurelio_sim_2
    - sensor.mobile_aurelio_total_rx_gb
    - sensor.mobile_aurelio_total_tx_gb
    - sensor.mobile_aurelio_volume_level_alarm
    - sensor.mobile_aurelio_volume_level_call
    - sensor.mobile_aurelio_volume_level_music
    - sensor.mobile_aurelio_volume_level_ringer
    - sensor.mobile_aurelio_wifi_frequency
    - sensor.mobile_aurelio_wifi_ip_address
    - sensor.mobile_aurelio_wifi_link_speed
    - sensor.mobile_aurelio_wifi_signal_strength
    - sensor.mobile_battery_level
    - sensor.mobile_battery_state
    - sensor.mobile_bluetooth_connection
    - sensor.mobile_camila_battery_level
    - sensor.mobile_camila_battery_state
    - sensor.mobile_camila_bluetooth_connection
    - sensor.mobile_camila_current_time_zone
    - sensor.mobile_camila_current_version
    - sensor.mobile_camila_detected_activity
    - sensor.mobile_camila_do_not_disturb_sensor
    - sensor.mobile_camila_external_storage
    - sensor.mobile_camila_geocoded_location
    - sensor.mobile_camila_internal_storage
    - sensor.mobile_camila_last_notification
    - sensor.mobile_camila_last_reboot
    - sensor.mobile_camila_last_update_trigger
    - sensor.mobile_camila_light_sensor
    - sensor.mobile_camila_mobile_rx_gb
    - sensor.mobile_camila_mobile_tx_gb
    - sensor.mobile_camila_phone_state
    - sensor.mobile_camila_pressure_sensor
    - sensor.mobile_camila_proximity_sensor
    - sensor.mobile_camila_public_ip_address
    - sensor.mobile_camila_ringer_mode
    - sensor.mobile_camila_sim_1
    - sensor.mobile_camila_sim_2
    - sensor.mobile_camila_steps_sensor
    - sensor.mobile_camila_total_rx_gb
    - sensor.mobile_camila_total_tx_gb
    - sensor.mobile_camila_volume_level_alarm
    - sensor.mobile_camila_volume_level_call
    - sensor.mobile_camila_volume_level_music
    - sensor.mobile_camila_volume_level_ringer
    - sensor.mobile_camila_wifi_frequency
    - sensor.mobile_camila_wifi_ip_address
    - sensor.mobile_camila_wifi_link_speed
    - sensor.mobile_camila_wifi_signal_strength
    - sensor.mobile_detected_activity
    - sensor.mobile_geocoded_location
    - sensor.mobile_internal_storage
    - sensor.mobile_last_reboot
    - sensor.mobile_light_sensor
    - sensor.mobile_pressure_sensor
    - sensor.mobile_proximity_sensor
    - sensor.mobile_ringer_mode
    - sensor.mobile_steps_sensor
    - sensor.mobile_wifi_connection
    - sensor.motion_hall_battery
    - sensor.motion_hall_linkquality
    - sensor.motion_livingroom_1_battery
    - sensor.motion_livingroom_1_linkquality
    - sensor.motion_side_external_battery
    - sensor.motion_side_external_illuminance
    - sensor.motion_side_external_illuminance_lux
    - sensor.motion_side_external_linkquality
    - sensor.motion_stairs_battery
    - sensor.motion_stairs_illuminance
    - sensor.motion_stairs_illuminance_lux
    - sensor.motion_stairs_linkquality
    - sensor.plug_bedroom_1_linkquality
    - sensor.plug_bedroom_2_linkquality
    - sensor.processor_use_percent
    - sensor.script_count
    - sensor.sensor_count
    - sensor.switch_count
    - sensor.switch_pool_lights_linkquality
    - sensor.switch_side_ligth_hall_linkquality
    - sensor.switch_side_ligth_stairs_linkquality
    - sensor.switch_wall_bathroom_linkquality
    - sensor.switch_wall_bedroom_linkquality
    - sensor.switch_wall_garden_linkquality
    - sensor.switch_wall_hall_3_linkquality
    - sensor.switch_wall_kitchen_linkquality
    - sensor.switch_wall_laboratory_linkquality
    - sensor.switch_wall_livingroom_linkquality
    - sensor.tarifa_fora_ponta
    - sensor.tarifa_intermediario
    - sensor.tarifa_ponta
    - sensor.temperature_bathroom_battery
    - sensor.temperature_bathroom_humidity
    - sensor.temperature_bathroom_linkquality
    - sensor.temperature_bathroom_pressure
    - sensor.time
    - sensor.time_date
    - sensor.time_online
    - sensor.time_utc
    - sensor.tracker_count
    - sensor.zigbee2mqtt_bridge_state
    - sensor.zigbee2mqtt_version
    - sensor.zwave_count
  # domains:
  #   - sun
  #   - binary_sensor
  #   - media_player
  #   - input_boolean
  #   - input_datetime
  #   - input_number
  #   - input_select
  #   - input_text
  #   - camera
  #   - script
  #     - automation
