# - platform: broadlink
#   host: !secret broadlink_host
#   mac: !secret broadlink_mac
#   timeout: 15
#   switches:
#     tv_living_room_2:
#       friendly_name: Televisão da sala
#       command_on: 'JgCEAFYfDxwQDg8OEBweDhAODw4QDg8OEA4PDg4QDw4PDw8ODw4dDxAcEA4PAAqwWBwQHBAODw4QHB4OEA4PDhAODw4QDg8ODhAPDg8ODhAPDh0PEBwOEA8ACrBYHA4eEA4PDhAcHQ8QDg8OEA4PDhAODw4QDg8ODw4QDg4PHQ8OHg4QDwANBQAAAAA='
#       command_off: 'JgCEAFYfDxwQDg8OEBweDhAODw4QDg8OEA4PDg4QDw4PDw8ODw4dDxAcEA4PAAqwWBwQHBAODw4QHB4OEA4PDhAODw4QDg8ODhAPDg8ODhAPDh0PEBwOEA8ACrBYHA4eEA4PDhAcHQ8QDg8OEA4PDhAODw4QDg8ODw4QDg4PHQ8OHg4QDwANBQAAAAA='
#     tv_bedroom:
#       command_on: 'JgAYAVASKBMVEicUFRIoExUSFBMpEhUTEhUUExUAA0tOFCYVExQmFRMUJxQUExQTJxQUExMUFBQSAANOThQnFBMUJhUTFCYVExQTFCcUFBMTFRMUEwADTU4UJxQUEycUFBMnFBQTFBMnFBQTExUTFBMAA05NFCcUFBMnFBQTJxQUExQTJxQUExQUExQTAANNThQnFBMUJxQTFCcUFBMUFCcTExUTFBMUFAADTE8TJxQUEycUFBMnFBQTFBQnExQUExQTFBQAA0xOFCgTFBMnFBQTJxQTFBQUJhUTFBMUExQUAANMThUmFBQUJxMUFCcTExUTFCYVExQTFBQTFAADTU0VJhQUFCYUFBQnExMVExQmFRMUExQUExMADQU='
#       command_off: 'JgDgAE4UJxQTFCYVExQmFRMUExQnFBQTFBMUFBMAA01NFSYUFBQmFRMUJxQTFBMUJxQTFBQTFBMUAANNThQnFBMUJhUTFCcUExQTFCcUExQUExQTFAADTU4UJxQTFCYVExQnFBMUExQnFBMUFBMUFBMAA01OFCYVExQmFRMUJhUTFBMUJxQUExQTFBQTAANNThQnFBMUJhUTFCYVExQUEycUFBMUFBMUEwADTU4UJxQUEycUFBMnFBQTFBMnFBQTFBQTFBMAA01PEycUFBMnFBQTJxQUExQTKBMUExQUExQTAA0FAAAAAAAAAAA='
- platform: template
  switches:
    tv_living_room:
      friendly_name: Televisão da sala
      value_template: "{% if is_state('media_player.amazon_fire_tv', 'off') %}off{% else %}on{% endif %}"
      icon_template: >-
          {% if is_state('media_player.amazon_fire_tv', 'off') %}
            mdi:television-classic-off
          {% else %}
            mdi:television-classic
          {% endif %}
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.amazon_fire_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.amazon_fire_tv
- platform: circadian_lighting
  name: Luzes Janela (Circadian)
  lights_ct:
    - light.lamps_living_room_window
- platform: circadian_lighting
  name: Luzes TV (Circadian)
  lights_ct:
    - light.lamps_living_room_tv
- platform: circadian_lighting
  name: Luzes Quarto (Circadian)
  lights_ct:
    - light.lamps_bedroom
- platform: circadian_lighting
  name: Luzes Sala (Circadian)
  lights_ct:
    - light.lamps_living_room
