mysql_host: mysql://xxx@0.0.0.0:3306/homeassistant?charset=utf8
telegram_key: xxx:xxx
alarm_code: 1111
fire_tv: 0.0.0.0
telegram_aurelio: 123
telegram_camila: 123
telegram_allowed_chat_ids:
  - 611383381
