# Quadro de força
energy_watts_daily:
  source: sensor.je05_pativa_total
  cycle: daily
  offset: '00:00:00'
energy_watts_weekly:
  source: sensor.je05_pativa_total
  cycle: weekly
energy_watts_monthly:
  source: sensor.je05_pativa_total
  cycle: monthly
  offset:
    days: 1
    hours: 0
    minutes: 0
energy_daily:
  source: sensor.je05_kwh_total
  cycle: daily
  offset: '00:00:00'
energy_weekly:
  source: sensor.je05_kwh_total
  cycle: weekly
energy_monthly:
  source: sensor.je05_kwh_total
  cycle: monthly
  offset:
    days: 1
    hours: 0
    minutes: 0

# Piscina
energy_pool_machine_daily:
  source: sensor.poolmachine_total_daily_energy
  cycle: daily
  offset: '00:00:00'
energy_pool_machine_weekly:
  source: sensor.poolmachine_total_daily_energy
  cycle: weekly
energy_pool_machine_monthly:
  source: sensor.poolmachine_total_daily_energy
  cycle: monthly
  offset:
    days: 1
    hours: 0
    minutes: 0
energy_watts_pool_machine_daily:
  source: sensor.poolmachine_wattage
  cycle: daily
  offset: '00:00:00'
energy_watts_pool_machine_weekly:
  source: sensor.poolmachine_wattage
  cycle: weekly
energy_watts_pool_machine_monthly:
  source: sensor.poolmachine_wattage
  cycle: monthly
  offset:
    days: 1
    hours: 0
    minutes: 0

# Maquina de lavar
energy_washing_machine_daily:
  source: sensor.washing_machine_total_daily_energy
  cycle: daily
  offset: '00:00:00'
energy_washing_machine_weekly:
  source: sensor.washing_machine_total_daily_energy
  cycle: weekly
energy_washing_machine_monthly:
  source: sensor.washing_machine_total_daily_energy
  cycle: monthly
  offset:
    days: 1
    hours: 0
    minutes: 0
energy_watts_washing_machine_daily:
  source: sensor.washing_machine_power
  cycle: daily
  offset: '00:00:00'
energy_watts_washing_machine_weekly:
  source: sensor.washing_machine_power
  cycle: weekly
energy_watts_washing_machine_monthly:
  source: sensor.washing_machine_power
  cycle: monthly
  offset:
    days: 1
    hours: 0
    minutes: 0
