- id: turn_on_the_light_external_laundry_2
  alias: turn_on_the_light_external_laundry_2
  trigger:
    - platform: state
      entity_id: binary_sensor.door_laundry_contact
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.turn_on_the_light_external
          state: 'on'
        - condition: state
          entity_id: switch.switch_wall_laundry_bottom
          state: 'off'
        - condition: state
          entity_id: binary_sensor.motion_laundry_occupancy
          state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_wall_laundry_bottom
    - service: automation.turn_on
      entity_id: automation.turn_off_the_light_external_laundry_2

- id: turn_off_the_light_external_laundry_2
  alias: turn_off_the_light_external_laundry_2
  initial_state: off
  trigger:
    - platform: state
      entity_id: binary_sensor.door_laundry_contact
      from: 'on'
      to: 'off'
      for: '00:00:30'
  condition:
  action:
    - service: switch.turn_off
      entity_id: switch.switch_wall_laundry_bottom
    - service: automation.turn_off
      entity_id: automation.turn_off_the_light_external_laundry_2


- id: turn_on_the_light_external_2
  alias: turn_on_the_light_external_2
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_side_external_2_occupancy
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.turn_on_light_motion
          state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_wall_laundry_center
    - service: automation.turn_on
      entity_id: automation.turn_off_the_light_external_2

- id: turn_off_the_light_external_2
  alias: turn_off_the_light_external_2
  initial_state: off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_side_external_2_occupancy
      from: 'on'
      to: 'off'
      for: '00:00:30'
  condition:
  action:
    - service: switch.turn_off
      entity_id: switch.switch_wall_laundry_center
    - service: automation.turn_off
      entity_id: automation.turn_off_the_light_external_2


- id: turn_on_the_light_external_laundry
  alias: turn_on_the_light_external_laundry
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_side_external_laundry_1_occupancy
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.turn_on_the_light_external
          state: 'on'
        - condition: state
          entity_id: switch.switch_wall_laundry_center
          state: 'off'
        - condition: state
          entity_id: input_boolean.turn_on_light_motion
          state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_wall_laundry_center
    - service: automation.turn_on
      entity_id: automation.turn_off_the_light_external_laundry

- id: turn_off_the_light_external_laundry
  alias: turn_off_the_light_external_laundry
  initial_state: off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_side_external_laundry_1_occupancy
      from: 'on'
      to: 'off'
      for: '00:00:30'
  condition:
  action:
    - service: switch.turn_off
      entity_id: switch.switch_wall_laundry_center
    - service: automation.turn_off
      entity_id: automation.turn_off_the_light_external_laundry
