
- id: turn_off_the_light_with_door_garden_is_closed
  alias: turn_off_the_light_with_door_garden_is_closed
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_garden_contact
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.switch_wall_garden_top
        - switch.switch_wall_garden_center
