- id: turn_on_the_light_external_1
  alias: turn_on_the_light_external_1
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_side_external_1_occupancy
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.turn_on_the_light_external
          state: 'on'
        - condition: state
          entity_id: switch.switch_wall_hall_2_l3_external_side
          state: 'off'
        - condition: state
          entity_id: input_boolean.turn_on_light_motion
          state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_wall_hall_2_l3_external_side
    - service: automation.turn_on
      entity_id: automation.turn_off_the_light_external_1

- id: turn_off_the_light_external_1
  alias: turn_off_the_light_external_1
  initial_state: off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_side_external_1_occupancy
      from: 'on'
      to: 'off'
      for: '00:00:30'
  condition:
  action:
    - service: switch.turn_off
      entity_id: switch.switch_wall_hall_2_l3_external_side
    - service: automation.turn_off
      entity_id: automation.turn_off_the_light_external_1
