- id: turn_on_the_light_garage_when_door_opened
  alias: turn_on_the_light_garage_when_door_opened
  trigger:
    - platform: state
      entity_id: binary_sensor.door_hall_contact
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.turn_on_the_light_external
          state: 'on'
        - condition: state
          entity_id: switch.switch_wall_hall_1_l1_garage
          state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_wall_hall_1_l1_garage
    - service: automation.turn_on
      entity_id: automation.turn_off_the_light_garage_when_door_closed

- id: turn_off_the_light_garage_when_door_closed
  alias: turn_off_the_light_garage_when_door_closed
  initial_state: off
  trigger:
    - platform: state
      entity_id: binary_sensor.door_hall_contact
      from: 'on'
      to: 'off'
      for: '00:02:00'
  condition:
  action:
    - service: switch.turn_off
      entity_id: switch.switch_wall_hall_1_l1_garage
    - service: automation.turn_off
      entity_id: automation.turn_off_the_light_garage_when_door_closed



- id: turn_on_the_light_garge_when_motion_detected
  alias: turn_on_the_light_garge_when_motion_detected
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_side_external_garage_occupancy
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.turn_on_the_light_external
          state: 'on'
        - condition: state
          entity_id: switch.switch_wall_hall_1_l1_garage
          state: 'off'
        - condition: state
          entity_id: input_boolean.turn_on_light_motion
          state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_wall_hall_1_l1_garage
    - service: automation.turn_on
      entity_id: automation.turn_off_the_light_garge_when_motion_not_detected

- id: turn_off_the_light_garge_when_motion_not_detected
  alias: turn_off_the_light_garge_when_motion_not_detected
  initial_state: off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_side_external_garage_occupancy
      from: 'on'
      to: 'off'
      for: '00:00:30'
  condition:
  action:
    - service: switch.turn_off
      entity_id: switch.switch_wall_hall_1_l1_garage
    - service: automation.turn_off
      entity_id: automation.turn_off_the_light_garge_when_motion_not_detected
