substitutions:
  hostname: "cam_house_machine"
  ssid_ap: "cam_house_machine"
  versao: "1.0"

esphome:
  name: cam_house_machine
  platform: ESP8266
  board: nodemcuv2
  esp8266_restore_from_flash: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  ap:
    ssid: "$ssid_ap"
    password: !secret AP_mode_pass
# mqtt:
  # broker: 192.168.68.109

captive_portal:


logger:
  baud_rate: 0

mqtt:
  broker: !secret mqtt_broker
  discovery: true

ota:
  password: !secret ota_pass

time:
  - platform: sntp
    id: my_time
